server:
  port: 8080
  # servlet:
  #   context-path: /vanChuyen
spring:
  datasource:
    url: ${DB_URL_MYSQL:jdbc:mysql://localhost:3306/transport_1?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    # defer-datasource-initialization: true
  # sql:
  #   init:
  #     mode: always  # Luôn chạy file data.sql
  #     platform: mysql
#    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port:  ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenquanglinh0509@gmail.com
    password: aoou cjxq wgoi qsrz
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
    default-encoding: UTF-8
    # Cấu hình Thymeleaf
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  # Cấu hình async
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
jwt:  
  signerKey: bvkfSG5tgcc6kHcMWz6VpgyEjCmg16w8EzZv5mPs3KT4Tt1lS3AhkkOBE3oabTJ8
  vaild-duration: 18000
  refresh-duration: 86400
logging:
  level:
    com.vanchuyen: DEBUG
    org.hibernate.SQL: DEBUG
app:
  file:
    upload-dir: uploads  # Thư mục gốc để lưu file
    max-size: 5242880    # 5MB in bytes